services:
  postgres:
    image: postgres:15
    container_name: recipe_postgres
    environment:
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: recipe_pass
      POSTGRES_DB: recipe_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: